name: Unit Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run unit tests with coverage
        run: mvn -B clean verify

      - name: Generate coverage summary
        uses: mikepenz/action-jacoco-report@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          paths: |
            **/target/site/jacoco/jacoco.xml
          title: JaCoCo Coverage Report

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco
